/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:314242:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:314242:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:819577:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button2:819577:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:990180:
  println("button3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button3:990180:

public void button4_click1(GButton source, GEvent event) { //_CODE_:button4:573903:
  println("button4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button4:573903:

public void button5_click1(GButton source, GEvent event) { //_CODE_:button5:661384:
  println("button5 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button5:661384:

public void button6_click1(GButton source, GEvent event) { //_CODE_:button6:986537:
  println("button6 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button6:986537:

public void button7_click1(GButton source, GEvent event) { //_CODE_:button7:298680:
  println("button7 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button7:298680:

public void button8_click1(GButton source, GEvent event) { //_CODE_:button8:532317:
  println("button8 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button8:532317:

public void button9_click1(GButton source, GEvent event) { //_CODE_:button9:773446:
  println("button9 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button9:773446:

public void button10_click1(GButton source, GEvent event) { //_CODE_:button10:657414:
  println("button10 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button10:657414:

public void button11_click1(GButton source, GEvent event) { //_CODE_:button11:901145:
  println("button11 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button11:901145:

public void button12_click1(GButton source, GEvent event) { //_CODE_:button12:722060:
  println("button12 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button12:722060:

public void button13_click1(GButton source, GEvent event) { //_CODE_:button13:474411:
  println("button13 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button13:474411:

public void button14_click1(GButton source, GEvent event) { //_CODE_:button14:340894:
  println("button14 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button14:340894:

public void button15_click1(GButton source, GEvent event) { //_CODE_:button15:438548:
  println("button15 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button15:438548:

public void button16_click1(GButton source, GEvent event) { //_CODE_:button16:723419:
  println("button16 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button16:723419:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 5, 230, 80, 30);
  button1.setText("Feed");
  button1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 90, 230, 80, 30);
  button2.setText("Treat");
  button2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 5, 265, 80, 30);
  button3.setText("Play");
  button3.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button3.addEventHandler(this, "button3_click1");
  button4 = new GButton(this, 90, 265, 80, 30);
  button4.setText("Talk");
  button4.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  button4.addEventHandler(this, "button4_click1");
  button5 = new GButton(this, 305, 231, 80, 30);
  button5.setText("Feed");
  button5.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button5.addEventHandler(this, "button5_click1");
  button6 = new GButton(this, 390, 229, 80, 30);
  button6.setText("Treat");
  button6.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button6.addEventHandler(this, "button6_click1");
  button7 = new GButton(this, 305, 265, 80, 30);
  button7.setText("Play");
  button7.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button7.addEventHandler(this, "button7_click1");
  button8 = new GButton(this, 390, 265, 80, 30);
  button8.setText("Talk");
  button8.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  button8.addEventHandler(this, "button8_click1");
  button9 = new GButton(this, 5, 530, 80, 30);
  button9.setText("Feed");
  button9.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button9.addEventHandler(this, "button9_click1");
  button10 = new GButton(this, 90, 530, 80, 30);
  button10.setText("Treat");
  button10.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button10.addEventHandler(this, "button10_click1");
  button11 = new GButton(this, 5, 566, 80, 30);
  button11.setText("Play");
  button11.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button11.addEventHandler(this, "button11_click1");
  button12 = new GButton(this, 90, 565, 80, 30);
  button12.setText("Talk");
  button12.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button12.addEventHandler(this, "button12_click1");
  button13 = new GButton(this, 305, 530, 80, 30);
  button13.setText("Feed");
  button13.setLocalColorScheme(GCScheme.RED_SCHEME);
  button13.addEventHandler(this, "button13_click1");
  button14 = new GButton(this, 390, 530, 80, 30);
  button14.setText("Treat");
  button14.setLocalColorScheme(GCScheme.RED_SCHEME);
  button14.addEventHandler(this, "button14_click1");
  button15 = new GButton(this, 305, 565, 80, 30);
  button15.setText("Play");
  button15.setLocalColorScheme(GCScheme.RED_SCHEME);
  button15.addEventHandler(this, "button15_click1");
  button16 = new GButton(this, 390, 565, 80, 30);
  button16.setText("Talk");
  button16.setLocalColorScheme(GCScheme.RED_SCHEME);
  button16.addEventHandler(this, "button16_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
GButton button4; 
GButton button5; 
GButton button6; 
GButton button7; 
GButton button8; 
GButton button9; 
GButton button10; 
GButton button11; 
GButton button12; 
GButton button13; 
GButton button14; 
GButton button15; 
GButton button16; 
